export enum Emojis {
    TADA = ':tada:',
    HBIRT = ':100:',
    SMILE = ':smile:',
    THUMB_UP = ':thums_up:',
    HEART = ':heart:',
    SPARKLE = ':sparkles:',
    EXCLAMATION = ':exclamation:',
    QUESTION = ':question:',
    PUNCH = ':punch:',
    FIRE = ':fire:',
    ZAP = ':zap:',
    OCTOCAT = ':octocat:',
    SAVE = ':floppy_disk:',
    LOCK = ':lock:',
    UNLOCK = ':unlock:',
    FOLDER = ':file_folder:',
    CAMERA = ':camera:',
    SPEECH_BALLO0N = ':speech_balloon:',
    THOUGHT_BALLO0N = ':thought_balloon:'
}